version: '3.8'

services:
  web:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8086:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NVIDIA_VISIBLE_DEVICES=all
      - MINERU_DEVICE=cuda
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia

  redis:
    image: harbor.shmtu.edu.cn/library/redis:alpine
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
